### PR TITLE
Merge from develop for new release 2.9.4

### PR DESCRIPTION
**Pull request by rikterbeek**

### CODE REVIEW

**Comment by rikterbeek** [comment]
Before pulling make sure fee module version is updated

**Comment by JeroenBoersma** [comment]
PR coming up

**Comment by JeroenBoersma** [comment]
could work faster

**Comment by JeroenBoersma** [comment]
See #845

**Comment by rikterbeek** [comment]
Thanks!

**Comment by rikterbeek** [comment]
lets wait for #844 then I will do the release.

**Comment by cstergianos** [comment]
@rikterbeek Is this ready for a release? :)

**Comment by rikterbeek** [comment]
Hi @cstergianos,

Yes doing the release.

Regards,
Rik
Adyen

**Pull request merged**
