### PR TITLE
Version bump to 2.9.4

### PR DESCRIPTION
**Pull request by JeroenBoersma**
* prepare version bump for composer

### CODE REVIEW

**Comment by JeroenBoersma** [comment]
@rikterbeek here it is as noted in #841

**Comment by JeroenBoersma** [comment]
please release this, would be awesome :+1:

**Comment by rikterbeek** [comment]
Hi @JeroenBoersma,

Yes will do. Thanks for the PR!

Regards,
Rik

**Comment by lancergr** [comment]
Hi @JeroenBoersma 

Can you do a version update on the Fee module as well?

Regards,
Giorgos
Adyen

**Comment by JeroenBoersma** [comment]
Sure, didn't know they were coupled :)

**Pull request merged**
