### PR TITLE
here is my code for payment percentage fee and refunds for creditmemo

### PR DESCRIPTION
**Pull request by leonhelmus**

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi @leonhelmus,

Thanks for sharing this code. I can not accept this pull request because you have built it into a separate module. I will look at this code and check if we can include it into the adyen_fee module.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @leonhelmus,

The code is looking good could you move the changes from the AthleteMods_Adyen module into the Adyen_Fee module ?

Regards,
Rik
Adyen

**Comment by leonhelmus** [comment]
yes, i could. But will you use the same code ?

**Comment by rikterbeek** [comment]
Hi @leonhelmus,

Yes then I will accept your pull request.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
@leonhelmus,

What is the status did you have time to include it into the fee module ?

Regards,
Rik
Adyen

**Comment by leonhelmus** [comment]
i cant add it this week and was swammed with work. I can get to it next week. At this time im on vacation. I also modified some of my code so it will also work if you try to auto credit.

**Comment by rikterbeek** [comment]
Hi @leonhelmus,

That is fine thanks!

Regards,
Rik
Adyen

**Pull request closed without merging**
