### PR TITLE
Remove excessive rights and fixed modman file

### LINKED ISSUE #825: modman file
Hi,
I noticed that in 2.9.2 versione the modman file has no more "*" in all paths and this creates compatibility problems with others modules.
Can you revert modman file as in 2.9.1 version?
For example:

2.9.1 (correct)
app/code/community/Adyen/*                      app/code/community/Adyen/

2.9.2 (wrong)
app/code/community/Adyen/                       app/code/community/Adyen/

Thank you

### PR DESCRIPTION
**Pull request by JeroenBoersma**
* fixes #825 
* removed execute right on files

### CODE REVIEW

**Comment by sandermangel** [comment]
@rikterbeek could you take a look at this PR?
installation completely breaks in current version (2.9.3)

**Comment by rikterbeek** [comment]
HI @JeroenBoersma,

Thanks for the PR! looks good for me @sandermangel did the mean this change in PR is breaking installation or the current modman file is the problem ?

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
@rikterbeek sorry, I mean this fixes it :)

**Comment by JeroenBoersma** [comment]
Shall I create a new PR so we can also do a version bump ? @rikterbeek

**Pull request merged**
